# This is a basic workflow to help you get started with Actions

name: CI to Gitee

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: add Git infomations
        run: | 
          git config --global user.name 'wztlink1013' 
          git config --global user.email '2550374815@qq.com'

      - name: submit commit infomations
        run: |
          git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log

      - name: push Gitee repository
        env:
          Gitee_Pages: gitee.com/wztlink1013/uniapp-harryPotter-visualize.git
          Gitee_Token: ${{ secrets.GITEE_TOKEN }}
        run: |  
          git clone https://github.com/wztlink1013/uniapp-harryPotter-visualize.git github_repository
          git clone https://gitee.com/wztlink1013/uniapp-harryPotter-visualize.git gitee_repository
          cd github_repository
          rm -r .git
          cd ..
          mv gitee_repository/.git/ -f github_repository/
          mv github_repository/ -f gitee_repository/
          git status
          git add .
          git commit -m "remove to gitee_repository"
          git push --force --quiet "https://${Gitee_Token}@${Gitee_Pages}" master:master
